version: 2.1
# orbs - reusable packages for use
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions
jobs:
  build: #job name
    docker: # environment
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish: #known as the build and push
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: kiblykat/education-repository
      - docker/push: #pushes the image to the specified account in the environment variables
          image: kiblykat/education-repository
# workflows - defines what sequence will the jobs run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
